spring:
  application:
    name: proxy

server:
  port: 888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: routes,info,health

zuul:
  routes:
    service-one:
      path: /**
      serviceId: service-one
